spring:
  application:
    name: ai-agent
  profiles:
    active: local
  # PgVector
  #  datasource:
  #    url: xxx
  #    username: root
  #    password: pass
  ai:
    dashscope:
      api-key: https://bailian.console.aliyun.com/cn-beijing/?tab=model#/api-key
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    # mcp:
    #   client:
    #     sse:
    #       connections:
    #         server1:
    #           url: http://localhost:8124
    #     stdio:
    #       servers-configuration: classpath:mcp-servers.json
# PgVector
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v1/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.github.tianchenghang.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
search-api:
  api-key: https://www.searchapi.io/
logging:
  level:
    org.springframework.ai: DEBUG
